import { Metadata } from "next";
import "../../Styles.css";
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js Tutorial",
    template: "%s | Tutorial",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="m-0 p-0">
        <header className="bg-blue-400 p-4 ">
          <p>Header</p>
        </header>
        {children}
        <footer className="bg-slate-200 p-4">
          <p>footer</p>
        </footer>
      </body>
    </html>
  );
}
